### ISSUE TITLE
tp，虚弱也能记录就好了

### ISSUE THREAD

**Issue by L1cardo** [Knkajfw/PasteLikeDoinb#1]
点燃，疾跑，进化这些无伤大雅。
主要是tp，和虚弱对团战影响比较大，能记录这两个就好了。
当然！tp是首要需要支持的！
加油！做的很棒的一个软件！

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Knkajfw** [comment]
谢谢鼓励！
TP支持已在计划内，应该会在10.6版本TP改动后更新。
在此基础上，增加虚弱支持也不是难事~
