### ISSUE TITLE
快捷键支持

### ISSUE THREAD

**Issue by L1cardo** [Knkajfw/PasteLikeDoinb#2]
做了小型服务器，通过手机来实现想电脑发送命令，这个想法超级棒。
但是如果能自定义键盘快捷键，甚至鼠标快捷键（鼠标有很多按键）就更好了！
这样比手机操作方便些，而且手机耗电也能解决，打游戏时低头看手机也能避免。
electron实现快捷键应该不难的

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Knkajfw** [comment]
> 做了小型服务器，通过手机来实现想电脑发送命令，这个想法超级棒。
> 但是如果能自定义键盘快捷键，甚至鼠标快捷键（鼠标有很多按键）就更好了！
> 这样比手机操作方便些，而且手机耗电也能解决，打游戏时低头看手机也能避免。
> electron实现快捷键应该不难的
> 
> Sent from [PPHub](https://apps.apple.com/cn/app/id1314212521)

想法获得了认可非常开心！
会认真考虑关于快捷键的建议
目前作为初学者，对于全屏游戏条件下的快捷键和UI，还有很多不了解的地方
容我多多学习之后再做决定:p

再次感谢您能够反馈您的使用感受！

**Comment by L1cardo** [comment]
而且我发现你的app现在好像是连接的你自己的服务器（二维码指向你的域名），我ping了一下域名，结果没找到ip地址（想判断服务器的地址）
这样使用的人越来越多的话会给你造成负担，而且使用者可能会因为延迟而烦恼。
如果可以的话做成电脑与手机同一局域网下连接，不仅延迟低，对你的负担也低

**Comment by Knkajfw** [comment]
是的 有一个服务器在负责把手机和电脑联系起来 服务器位置当前不在国内 等域名备案完成后会考虑切换到国内

关于局域网连接，此前想法是，希望能实现两个设备不用在意网络环境，只要扫码就能连接（未来版本计划效仿Mimic把扫码也省掉)。目前使用人数还不多，延迟和负担看上去都还好。

如果你下载使用了这个app的话，请问在使用过程中已经有明显的延迟了吗？

**Comment by L1cardo** [comment]
我还没有实际到游戏中去体验，因为进入界面花了好长时间。
我不开代理就一直是下面的两个画面，等待了5min还是进不去。
即使开了代理，也是很慢，而且也有进不去的情况
![QQ截图20200322121802](https://user-images.githubusercontent.com/33802186/77242346-71b6df80-6c38-11ea-9288-9964354d95c7.png)
![2](https://user-images.githubusercontent.com/33802186/77242351-754a6680-6c38-11ea-85c2-d90227e31e8f.png)

**Comment by L1cardo** [comment]
或者你可以建立一个qq群，可能大家交流起来方便些

**Comment by Knkajfw** [comment]
> 或者你可以建立一个qq群，可能大家交流起来方便些

好主意！建好通知你！

**Comment by Knkajfw** [comment]
进不去的问题我自己偶尔也会遇到 没想到在你这里这么严重

app没有配置会走系统代理 应急可以试下proxifier之类的工具让它强行走代理

服务器迁到国内后还是没有改善的话再深入研究一下 成功连上之后 延迟应该完全能接受

**Comment by Knkajfw** [comment]
群号码
699702899

**Comment by Knkajfw** [comment]
由于Electron在Windows中注册的快捷键，在游戏中会无法触发，因此实现利用快捷键记录和发送技能目前不在短期开发目标当中。
