### ISSUE TITLE
给予管理员权限也不能在游戏内发送技能时间

### ISSUE THREAD

**Issue by DuKunAa** [Knkajfw/PasteLikeDoinb#8]
连接步骤完全按照教程，能获取到对局，但是记录技能后，不会打字发送

**Comment by Knkajfw** [comment]
根据您的描述应该连接和权限都不存在问题。请检查“发送这些技能”的选项，是否和你要发送的技能匹配。

**Comment by DuKunAa** [comment]
> 根据您的描述应该连接和权限都不存在问题。请检查“发送这些技能”的选项，是否和你要发送的技能匹配。

设置兼容性模式后可以正常使用了
